"""add_missing_indexes

Revision ID: 51b4f735d9de
Revises: 47fd0e00c59a
Create Date: 2026-06-26 23:38:47.843071

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '51b4f735d9de'
down_revision: Union[str, Sequence[str], None] = '47fd0e00c59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('ix_conn_plays_played_at', 'conn_plays', ['played_at'], unique=False)
    op.create_index('ix_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oauth_states_expires_at', table_name='oauth_states')
    op.drop_index('ix_conn_plays_played_at', table_name='conn_plays')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    # ### end Alembic commands ###
