"""initial schema

Revision ID: 58aee6475783
Revises: 
Create Date: 2026-06-23 23:30:17.582403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58aee6475783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_users',
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('global_name', sa.String(), nullable=True),
    sa.Column('avatar_hash', sa.String(), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('oauth_states',
    sa.Column('state_token', sa.String(), nullable=False),
    sa.Column('redirect_after', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('state_token')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('absolute_expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['discord_id'], ['discord_users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_discord_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('archived_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_discord_id'], ['discord_users.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('conn_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('tag_auto', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("status IN ('upcoming','used','graveyard')", name='ck_question_status'),
    sa.CheckConstraint("tag IN ('warm','secretive','reflective','tension','vulnerable','loyal')", name='ck_question_tag'),
    sa.CheckConstraint('length(text) <= 500', name='ck_question_len'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('used_by', sa.String(), nullable=True),
    sa.Column('used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['discord_users.discord_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['discord_users.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('game_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Partial unique indexes for game_members (allow re-adding deleted names / Discord IDs)
    op.create_index('uq_game_member_name_active', 'game_members', ['game_id', 'name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_game_member_discord_active', 'game_members', ['game_id', 'discord_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL AND discord_id IS NOT NULL'))
    op.create_table('game_memberships',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['discord_id'], ['discord_users.discord_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'discord_id')
    )
    op.create_table('conn_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('asker_member_id', sa.Integer(), nullable=False),
    sa.Column('target_member_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('asker_member_id != target_member_id', name='ck_no_self_pair'),
    sa.ForeignKeyConstraint(['asker_member_id'], ['game_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_member_id'], ['game_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'round_num', 'asker_member_id', name='uq_pairing_asker'),
    sa.UniqueConstraint('game_id', 'round_num', 'target_member_id', name='uq_pairing_target')
    )
    op.create_table('conn_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('played_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['played_by'], ['discord_users.discord_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['conn_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'round_num', name='uq_play_round')
    )
    op.create_table('conn_question_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=False),
    sa.Column('old_tag', sa.String(), nullable=False),
    sa.Column('edited_by', sa.String(), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['discord_users.discord_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['conn_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conn_state',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('current_question_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['current_question_id'], ['conn_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    # FK-path indexes for query performance
    op.create_index('ix_game_invites_game_id', 'game_invites', ['game_id'])
    op.create_index('ix_conn_questions_game_id', 'conn_questions', ['game_id'])
    op.create_index('ix_conn_pairings_game_id', 'conn_pairings', ['game_id'])
    op.create_index('ix_conn_plays_game_id', 'conn_plays', ['game_id'])
    op.create_index('ix_conn_question_edits_question_id', 'conn_question_edits', ['question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conn_state')
    op.drop_table('conn_question_edits')
    op.drop_table('conn_plays')
    op.drop_table('conn_pairings')
    op.drop_table('game_memberships')
    op.drop_table('game_members')
    op.drop_table('game_invites')
    op.drop_table('conn_questions')
    op.drop_table('games')
    op.drop_table('auth_sessions')
    op.drop_table('oauth_states')
    op.drop_table('discord_users')
    # ### end Alembic commands ###
