# Corvessa Connections starter question bank
# 38 questions, auto-tagged on insert via classify_sentiment

STARTER_QUESTIONS = [
    "What's the worst advice they've ever given you?",
    "When was the last time they genuinely surprised you?",
    "How do you think they see you—and are they right?",
    "What's something they do that makes you worry about them?",
    "What is something you've confided only in them?",
    "What's a promise you've made to them, spoken or unspoken?",
    "What do you think is their biggest weakness in a crisis?",
    "What's a habit or quirk of theirs that you find endearing?",
    "What do you think they dream about?",
    "What would you want them to say at your funeral?",
    "What's a secret you know about them that no one else does?",
    "What do you owe them that you can never repay?",
    "What do you argue about most, and who usually wins?",
    "What's a memory of them that always makes you smile?",
    "If you could change one thing about your relationship, what would it be?",
    "If they left the group tomorrow, what would you miss most?",
    "What's one thing you pretend not to notice about them?",
    "When was a time they let you down, and how did it affect you?",
    "What's the most important thing they've taught you about yourself?",
    "What do you think they would sacrifice everything for?",
    "What's one thing you need them to forgive you for?",
    "What's a topic you'd never bring up around them, and why?",
    "What's one thing they believe that you think is completely wrong?",
    "What's something you've learned from them, even if they don't know it?",
    "How would you describe them to a stranger?",
    "What's one thing about them that nobody else in the group notices?",
    "What's a line you think they would never cross—and do you believe it?",
    "What would you risk your life for on their behalf?",
    "What do you think they're most afraid of?",
    "What do they do that annoys you?",
    "What's the nicest thing they've ever done for you?",
    "What's one thing you wish they understood about you?",
    "What's something you admire about them that you'd never say out loud?",
    "Which of their powers/abilities/spells would you like to borrow for a day? Why?",
    "What are they hiding from the rest of the group?",
    "What's the bravest thing you've ever seen them do?",
    "What would you do if they were in mortal danger?",
    "What would your life look like if you'd never met them?",
]
